import os
from pathlib import Path
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

ROOT=Path(__file__).resolve().parents[1]
DATA_DIR=ROOT/'data'
DATA_DIR.mkdir(parents=True, exist_ok=True)
DEFAULT_SQLITE='sqlite:////tmp/shakweer_web.db'
DATABASE_URL=os.getenv('DATABASE_URL', DEFAULT_SQLITE)
connect_args={'check_same_thread':False} if DATABASE_URL.startswith('sqlite') else {'connect_timeout':5}
engine=create_engine(DATABASE_URL, pool_pre_ping=True, pool_recycle=1800, future=True, connect_args=connect_args)
SessionLocal=sessionmaker(bind=engine, autoflush=False, autocommit=False, expire_on_commit=False)

def db():
    s=SessionLocal()
    try: yield s
    finally: s.close()

def is_postgres(): return engine.dialect.name=='postgresql'

def q(s, sql, params=None):
    return [dict(r._mapping) for r in s.execute(text(sql), params or {}).fetchall()]

def one(s, sql, params=None):
    r=s.execute(text(sql), params or {}).first(); return dict(r._mapping) if r else None

def scalar(s, sql, params=None): return s.execute(text(sql), params or {}).scalar()

def audit(s,user_id,action,details):
    s.execute(text("INSERT INTO audit_logs(user_id,action,details) VALUES(:u,:a,:d)"),{'u':user_id,'a':action,'d':details})

def cash_balance(s): return float(scalar(s,"SELECT COALESCE(SUM(CASE WHEN direction='in' THEN amount ELSE -amount END),0) FROM cash_transactions") or 0)

def cash_move(s,direction,amount,category,source,user_id,notes='',ref_type=None,ref_id=None,created_at=None):
    s.execute(text("""INSERT INTO cash_transactions(direction,amount,category,source,reference_type,reference_id,notes,user_id,created_at)
    VALUES(:direction,:amount,:category,:source,:rt,:rid,:notes,:uid,COALESCE(:created_at,CURRENT_TIMESTAMP))"""),
    {'direction':direction,'amount':amount,'category':category,'source':source,'rt':ref_type,'rid':ref_id,'notes':notes,'uid':user_id,'created_at':created_at})

def init_schema():
    # SQLAlchemy-friendly schema. INTEGER PRIMARY KEY works as autoincrement in SQLite;
    # PostgreSQL uses identity columns below through dialect branching.
    with engine.begin() as c:
        if is_postgres():
            ddl='''
            CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
            CREATE TABLE IF NOT EXISTS users(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,full_name TEXT NOT NULL,role TEXT NOT NULL,is_active INTEGER DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,hourly_rate NUMERIC(14,2) DEFAULT 0,perm_pos INTEGER DEFAULT 1,perm_maintenance INTEGER DEFAULT 1,perm_inventory INTEGER DEFAULT 0,perm_customers INTEGER DEFAULT 1,perm_expenses INTEGER DEFAULT 0,perm_payroll INTEGER DEFAULT 0,perm_reports INTEGER DEFAULT 0,perm_audit INTEGER DEFAULT 0);
            CREATE TABLE IF NOT EXISTS categories(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT UNIQUE NOT NULL);
            CREATE TABLE IF NOT EXISTS products(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,barcode TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,unit TEXT DEFAULT 'قطعة',cost_price NUMERIC(14,2) DEFAULT 0,sell_price NUMERIC(14,2) DEFAULT 0,stock_qty NUMERIC(14,3) DEFAULT 0,min_stock NUMERIC(14,3) DEFAULT 5,image_path TEXT);
            CREATE TABLE IF NOT EXISTS customers(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,phone TEXT,address TEXT,balance NUMERIC(14,2) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS sales_invoices(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_number TEXT UNIQUE NOT NULL,customer_id INTEGER REFERENCES customers(id),user_id INTEGER NOT NULL REFERENCES users(id),payment_type TEXT NOT NULL,subtotal NUMERIC(14,2) DEFAULT 0,discount_amount NUMERIC(14,2) DEFAULT 0,total_amount NUMERIC(14,2) NOT NULL,paid_amount NUMERIC(14,2) DEFAULT 0,remaining_amount NUMERIC(14,2) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS sales_items(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_id INTEGER NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,product_id INTEGER NOT NULL REFERENCES products(id),quantity NUMERIC(14,3) NOT NULL,unit_price NUMERIC(14,2) NOT NULL,cost_price NUMERIC(14,2) DEFAULT 0,total_price NUMERIC(14,2) NOT NULL);
            CREATE TABLE IF NOT EXISTS cash_transactions(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,direction TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,category TEXT NOT NULL,source TEXT NOT NULL,reference_type TEXT,reference_id INTEGER,notes TEXT,user_id INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS customer_payments(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id INTEGER NOT NULL REFERENCES customers(id),user_id INTEGER NOT NULL REFERENCES users(id),amount NUMERIC(14,2) NOT NULL,notes TEXT,payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS maintenance_tickets(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ticket_number TEXT UNIQUE NOT NULL,customer_id INTEGER NOT NULL REFERENCES customers(id),device_type TEXT NOT NULL,device_model TEXT NOT NULL,serial_imei TEXT,problem_desc TEXT NOT NULL,accessories TEXT,pattern_lock TEXT,is_power_on INTEGER DEFAULT 1,is_screen_cracked INTEGER DEFAULT 0,is_water_damaged INTEGER DEFAULT 0,is_camera_working INTEGER DEFAULT 1,status TEXT DEFAULT 'received',estimated_cost NUMERIC(14,2) DEFAULT 0,discount_amount NUMERIC(14,2) DEFAULT 0,prepaid_amount NUMERIC(14,2) DEFAULT 0,final_cost NUMERIC(14,2) DEFAULT 0,technician_notes TEXT,user_id INTEGER NOT NULL REFERENCES users(id),received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,delivered_at TIMESTAMP);
            CREATE TABLE IF NOT EXISTS maintenance_parts(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ticket_id INTEGER NOT NULL REFERENCES maintenance_tickets(id) ON DELETE CASCADE,product_id INTEGER NOT NULL REFERENCES products(id),quantity NUMERIC(14,3) NOT NULL,unit_cost NUMERIC(14,2) DEFAULT 0,unit_price NUMERIC(14,2) DEFAULT 0);
            CREATE TABLE IF NOT EXISTS maintenance_payments(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ticket_id INTEGER NOT NULL REFERENCES maintenance_tickets(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id),amount NUMERIC(14,2) NOT NULL,notes TEXT,payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS expenses(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),category TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,notes TEXT,expense_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS employees(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,full_name TEXT NOT NULL,phone TEXT,job_title TEXT,basic_salary NUMERIC(14,2) DEFAULT 0,is_active INTEGER DEFAULT 1);
            CREATE TABLE IF NOT EXISTS attendance(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),clock_in TIMESTAMP NOT NULL,clock_out TIMESTAMP,total_hours NUMERIC(10,2) DEFAULT 0,hourly_rate NUMERIC(14,2) DEFAULT 0,total_wage NUMERIC(14,2) DEFAULT 0,is_settled INTEGER DEFAULT 0,notes TEXT);
            CREATE TABLE IF NOT EXISTS weekly_wages(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),amount NUMERIC(14,2) NOT NULL,period_start DATE,period_end DATE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS payroll(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id),user_id INTEGER NOT NULL REFERENCES users(id),month_year TEXT NOT NULL,net_paid NUMERIC(14,2) NOT NULL,payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS cashier_advances(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),amount NUMERIC(14,2) NOT NULL,notes TEXT,is_deducted INTEGER DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS net_faults(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,subscriber_name TEXT NOT NULL,phone TEXT,fault_desc TEXT NOT NULL,status TEXT DEFAULT 'معلق',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS daily_orders(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_details TEXT NOT NULL,status TEXT DEFAULT 'قيد التنفيذ',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS product_returns(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_number TEXT NOT NULL,product_id INTEGER NOT NULL REFERENCES products(id),quantity NUMERIC(14,3) NOT NULL,refund_amount NUMERIC(14,2) NOT NULL,reason TEXT,user_id INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS whatsapp_messages(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ticket_id INTEGER,customer_id INTEGER,phone TEXT NOT NULL,event_type TEXT NOT NULL,message_body TEXT NOT NULL,status TEXT DEFAULT 'pending',provider_message_id TEXT,error TEXT,sent_at TIMESTAMP,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),action TEXT NOT NULL,details TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            '''
        else:
            ddl='''
            CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
            CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,full_name TEXT NOT NULL,role TEXT NOT NULL,is_active INTEGER DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,hourly_rate REAL DEFAULT 0,perm_pos INTEGER DEFAULT 1,perm_maintenance INTEGER DEFAULT 1,perm_inventory INTEGER DEFAULT 0,perm_customers INTEGER DEFAULT 1,perm_expenses INTEGER DEFAULT 0,perm_payroll INTEGER DEFAULT 0,perm_reports INTEGER DEFAULT 0,perm_audit INTEGER DEFAULT 0);
            CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL);
            CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,barcode TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category_id INTEGER,unit TEXT DEFAULT 'قطعة',cost_price REAL DEFAULT 0,sell_price REAL DEFAULT 0,stock_qty REAL DEFAULT 0,min_stock REAL DEFAULT 5,image_path TEXT);
            CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,address TEXT,balance REAL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS sales_invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_number TEXT UNIQUE NOT NULL,customer_id INTEGER,user_id INTEGER NOT NULL,payment_type TEXT NOT NULL,subtotal REAL DEFAULT 0,discount_amount REAL DEFAULT 0,total_amount REAL NOT NULL,paid_amount REAL DEFAULT 0,remaining_amount REAL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS sales_items(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER NOT NULL,product_id INTEGER NOT NULL,quantity REAL NOT NULL,unit_price REAL NOT NULL,cost_price REAL DEFAULT 0,total_price REAL NOT NULL);
            CREATE TABLE IF NOT EXISTS cash_transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,direction TEXT NOT NULL,amount REAL NOT NULL,category TEXT NOT NULL,source TEXT NOT NULL,reference_type TEXT,reference_id INTEGER,notes TEXT,user_id INTEGER NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS customer_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,amount REAL NOT NULL,notes TEXT,payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS maintenance_tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_number TEXT UNIQUE NOT NULL,customer_id INTEGER NOT NULL,device_type TEXT NOT NULL,device_model TEXT NOT NULL,serial_imei TEXT,problem_desc TEXT NOT NULL,accessories TEXT,pattern_lock TEXT,is_power_on INTEGER DEFAULT 1,is_screen_cracked INTEGER DEFAULT 0,is_water_damaged INTEGER DEFAULT 0,is_camera_working INTEGER DEFAULT 1,status TEXT DEFAULT 'received',estimated_cost REAL DEFAULT 0,discount_amount REAL DEFAULT 0,prepaid_amount REAL DEFAULT 0,final_cost REAL DEFAULT 0,technician_notes TEXT,user_id INTEGER NOT NULL,received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,delivered_at TIMESTAMP);
            CREATE TABLE IF NOT EXISTS maintenance_parts(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER NOT NULL,product_id INTEGER NOT NULL,quantity REAL NOT NULL,unit_cost REAL DEFAULT 0,unit_price REAL DEFAULT 0);
            CREATE TABLE IF NOT EXISTS maintenance_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER NOT NULL,user_id INTEGER NOT NULL,amount REAL NOT NULL,notes TEXT,payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,category TEXT NOT NULL,amount REAL NOT NULL,notes TEXT,expense_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,phone TEXT,job_title TEXT,basic_salary REAL DEFAULT 0,is_active INTEGER DEFAULT 1);
            CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,clock_in TIMESTAMP NOT NULL,clock_out TIMESTAMP,total_hours REAL DEFAULT 0,hourly_rate REAL DEFAULT 0,total_wage REAL DEFAULT 0,is_settled INTEGER DEFAULT 0,notes TEXT);
            CREATE TABLE IF NOT EXISTS weekly_wages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount REAL NOT NULL,period_start DATE,period_end DATE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS payroll(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id INTEGER NOT NULL,user_id INTEGER NOT NULL,month_year TEXT NOT NULL,net_paid REAL NOT NULL,payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS cashier_advances(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount REAL NOT NULL,notes TEXT,is_deducted INTEGER DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS net_faults(id INTEGER PRIMARY KEY AUTOINCREMENT,subscriber_name TEXT NOT NULL,phone TEXT,fault_desc TEXT NOT NULL,status TEXT DEFAULT 'معلق',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS daily_orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_details TEXT NOT NULL,status TEXT DEFAULT 'قيد التنفيذ',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS product_returns(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_number TEXT NOT NULL,product_id INTEGER NOT NULL,quantity REAL NOT NULL,refund_amount REAL NOT NULL,reason TEXT,user_id INTEGER NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS whatsapp_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER,customer_id INTEGER,phone TEXT NOT NULL,event_type TEXT NOT NULL,message_body TEXT NOT NULL,status TEXT DEFAULT 'pending',provider_message_id TEXT,error TEXT,sent_at TIMESTAMP,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,action TEXT NOT NULL,details TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
            '''
        for statement in ddl.split(';'):
            if statement.strip(): c.exec_driver_sql(statement)
        for idx in [
            "CREATE INDEX IF NOT EXISTS idx_cash_created_direction ON cash_transactions(created_at,direction)",
            "CREATE INDEX IF NOT EXISTS idx_sales_created ON sales_invoices(created_at)",
            "CREATE INDEX IF NOT EXISTS idx_maint_status ON maintenance_tickets(status)",
            "CREATE INDEX IF NOT EXISTS idx_products_stock ON products(stock_qty,min_stock)",
            "CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON customer_payments(payment_date)",
            "CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date)",
            "CREATE INDEX IF NOT EXISTS idx_returns_invoice_product ON product_returns(invoice_number,product_id)",
            "CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at)",
        ]:
            c.exec_driver_sql(idx)
        if is_postgres():
            c.exec_driver_sql("CREATE UNIQUE INDEX IF NOT EXISTS ux_cash_auto_ref ON cash_transactions(reference_type,reference_id) WHERE reference_type IS NOT NULL AND reference_id IS NOT NULL")
        # Non-destructive v2+ migrations: keep every existing table/data and add only missing capabilities.
        migrations = {
            'net_faults': [
                ('priority',"TEXT DEFAULT 'متوسط'"), ('resolution_notes','TEXT'), ('resolved_at','TIMESTAMP'),
                ('assigned_to','INTEGER'), ('updated_at','TIMESTAMP')
            ],
            'daily_orders': [
                ('customer_name','TEXT'), ('phone','TEXT'), ('amount','NUMERIC(14,2) DEFAULT 0'),
                ('priority',"TEXT DEFAULT 'عادي'"), ('assigned_to','INTEGER'), ('due_at','TIMESTAMP'),
                ('notes','TEXT'), ('updated_at','TIMESTAMP')
            ],
            'cashier_advances': [
                ('deducted_at','TIMESTAMP'), ('deduction_notes','TEXT')
            ],
            'attendance': [
                ('shift_note','TEXT'), ('late_minutes','INTEGER DEFAULT 0'), ('overtime_hours','NUMERIC(10,2) DEFAULT 0')
            ],
            'users': [
                ('hourly_rate','NUMERIC(14,2) DEFAULT 0'), ('phone','TEXT')
            ],
            'products': [
                ('supplier','TEXT'), ('location','TEXT'), ('notes','TEXT'), ('updated_at','TIMESTAMP')
            ],
            'sales_invoices': [
                ('tax_amount','NUMERIC(14,2) DEFAULT 0'), ('payment_method',"TEXT DEFAULT 'cash'"), ('notes','TEXT')
            ],
        }
        for table, cols in migrations.items():
            existing={r[1] for r in c.exec_driver_sql(f"PRAGMA table_info({table})").fetchall()} if not is_postgres() else {r[0] for r in c.execute(text("SELECT column_name FROM information_schema.columns WHERE table_name=:t"),{'t':table}).fetchall()}
            for col, typ in cols:
                if col not in existing:
                    c.exec_driver_sql(f"ALTER TABLE {table} ADD COLUMN {col} {typ}")
        c.exec_driver_sql("CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,quantity REAL NOT NULL,movement_type TEXT NOT NULL,reference_type TEXT,reference_id INTEGER,notes TEXT,user_id INTEGER,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)" if not is_postgres() else "CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_id INTEGER NOT NULL,quantity NUMERIC(14,3) NOT NULL,movement_type TEXT NOT NULL,reference_type TEXT,reference_id INTEGER,notes TEXT,user_id INTEGER,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
        c.exec_driver_sql("CREATE TABLE IF NOT EXISTS cash_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,closed_at TIMESTAMP,opening_balance REAL DEFAULT 0,expected_balance REAL DEFAULT 0,actual_balance REAL,difference REAL,notes TEXT)" if not is_postgres() else "CREATE TABLE IF NOT EXISTS cash_sessions(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER NOT NULL,opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,closed_at TIMESTAMP,opening_balance NUMERIC(14,2) DEFAULT 0,expected_balance NUMERIC(14,2) DEFAULT 0,actual_balance NUMERIC(14,2),difference NUMERIC(14,2),notes TEXT)")
        c.exec_driver_sql("CREATE TABLE IF NOT EXISTS internet_bands(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,download_mbps REAL DEFAULT 0,upload_mbps REAL DEFAULT 0,description TEXT,is_active INTEGER DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)" if not is_postgres() else "CREATE TABLE IF NOT EXISTS internet_bands(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT UNIQUE NOT NULL,download_mbps NUMERIC(14,2) DEFAULT 0,upload_mbps NUMERIC(14,2) DEFAULT 0,description TEXT,is_active INTEGER DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
        for idx in [
            "CREATE INDEX IF NOT EXISTS idx_attendance_user_in ON attendance(user_id,clock_in)",
            "CREATE INDEX IF NOT EXISTS idx_faults_status ON net_faults(status)",
            "CREATE INDEX IF NOT EXISTS idx_orders_status ON daily_orders(status)",
            "CREATE INDEX IF NOT EXISTS idx_advances_user ON cashier_advances(user_id,is_deducted)",
            "CREATE INDEX IF NOT EXISTS idx_stock_product_date ON stock_movements(product_id,created_at)",
        ]: c.exec_driver_sql(idx)
        defaults={'shop_name':'SHAKWEER NET','shop_title':'مركز خدمات المحمول والكمبيوتر والصيانة','shop_phone':'01000000000','shop_address':'','receipt_footer':'شكراً لتعاملكم معنا | SHAKWEER NET','app_theme':'dark','currency':'جنيه'}
        for k,v in defaults.items(): c.execute(text("INSERT INTO settings(key,value) VALUES(:k,:v) ON CONFLICT(key) DO NOTHING"),{'k':k,'v':v})
        from .security import hash_password
        if not c.execute(text("SELECT 1 FROM users WHERE username='admin'")).first():
            c.execute(text("INSERT INTO users(username,password_hash,full_name,role,perm_pos,perm_maintenance,perm_inventory,perm_customers,perm_expenses,perm_payroll,perm_reports,perm_audit) VALUES('admin',:p,'مدير النظام','admin',1,1,1,1,1,1,1,1)"),{'p':hash_password('admin123')})
        if not c.execute(text("SELECT 1 FROM users WHERE username='cashier'")).first():
            c.execute(text("INSERT INTO users(username,password_hash,full_name,role,perm_pos,perm_maintenance,perm_inventory,perm_customers) VALUES('cashier',:p,'الكاشير','cashier',1,1,0,1)"),{'p':hash_password('123456')})
        for name in ['شاشات وقطع غيار الصيانة','إكسسوارات وشواحن وسماعات','جرابات ولاصقات حماية','سوفت وير وكابلات','شحن ودفع إلكتروني']:
            c.execute(text("INSERT INTO categories(name) VALUES(:n) ON CONFLICT(name) DO NOTHING"),{'n':name})
        if not c.execute(text("SELECT 1 FROM customers WHERE id=1")).first(): c.execute(text("INSERT INTO customers(id,name,phone,address,balance) VALUES(1,'عميل نقدي عام','-','-',0)"))

